---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedoommik
  namespace: kubedoom
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: kubedoommik
  template:
    metadata:
      labels:
        app: kubedoommik
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
      - image: storaxdev/kubedoom:0.5.0
        name: kubedoommik
        ports:
        - containerPort: 5900
          protocol: TCP

